version: '3.2'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./app/src
        target: /olimat/app/src
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: sh -c './bin/wait-for db:5432 -- npm run dev'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    networks:
      - frontend
      - backend
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: ./api
        target: /olimat/api
      - type: volume
        source: node_modules
        target: /olimat/api/node_modules
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev123
    networks:
      - backend
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
  pgadmin:
    image: fenglc/pgadmin4:2.0
    environment:
      # password 'admin'
      - DEFAULT_USER=admin
    networks:
      - backend
    ports:
      # host:container
      - 5050:5050

networks:
  frontend:
  backend:

volumes:
  db-data:
  node_modules:
