version: '3.2'

services:
  sut:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: sh -c './bin/wait-for api:3030 -- npm test'
    depends_on:
      - api
    environment:
      NODE_ENV: test
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c './bin/wait-for db:5432 -- npm start'
    depends_on:
      - db
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
    image: postgres:9.6.4-alpine
